/* eslint-disable */
/* This file is autogenerated, see codegen.yml */


      export interface PossibleTypesResultData {
        possibleTypes: {
          [key: string]: string[]
        }
      }
      const result: PossibleTypesResultData = {
  "possibleTypes": {
    "Node": [
      "BlogPost",
      "ProjectPost"
    ],
    "NodeConnection": [
      "BlogPostConnection",
      "NodeBelongsTo",
      "ProjectPostConnection"
    ],
    "NodeConnectionEdge": [
      "BlogPostEdge",
      "NodeBelongsToEdge",
      "ProjectPostEdge"
    ],
    "Post": [
      "BlogPost",
      "ProjectPost"
    ],
    "PostResource": [
      "PostAudio",
      "PostImage",
      "PostVideo"
    ]
  }
};
      export default result;
    
// Generated on 2022-02-14T22:47:16+00:00
